package com.payfunds.wallet.network.response_model.transaction

data class Item(
    val actions: List<Any>,
    val base_fee_per_gas: String,
    val block: Int,
    val confirmation_duration: List<Int>,
    val confirmations: Int,
    val created_contract: CreatedContract,
    val decoded_input: DecodedInput,
    val exchange_rate: Any,
    val fee: Fee,
    val from: From,
    val gas_limit: String,
    val gas_price: String,
    val gas_used: String,
    val has_error_in_internal_txs: Boolean,
    val hash: String,
    val max_fee_per_gas: String,
    val max_priority_fee_per_gas: String,
    val method: String?,
    val nonce: Int,
    val position: Int,
    val priority_fee: String,
    val raw_input: String,
    val result: String,
    val revert_reason: Any,
    val status: String,
    val timestamp: String,
    val to: To? = null,
    val token_transfers: Any,
    val token_transfers_overflow: Any,
    val tx_burnt_fee: String,
    val tx_tag: Any,
    val tx_types: List<String>,
    val type: Int,
    val value: String
)